/** Copyright 2015 Neil Edelman, distributed under the terms of the GNU General
 Public License, see copying.txt */

package ca.mcgill.ecse429.conformancetest.nplus;

import ca.mcgill.ecse429.conformancetest.statemodel.persistence.PersistenceStateMachine;
import ca.mcgill.ecse429.conformancetest.statemodel.State;
import ca.mcgill.ecse429.conformancetest.statemodel.StateMachine;
import ca.mcgill.ecse429.conformancetest.statemodel.Transition;

import java.util.function.Predicate;

import java.util.Iterator;
import java.io.File;

/** This automates generation of N+ test strategy given an XML file in a
 specific form representing code and the code itself. It does not generate sneak
 path test cases. (it would be really easy to do it?)

 @author	Neil
 @version	1.0, 2015-09
 @since		1.0, 2015-09 */
class Nplus {

	static final int EXIT_FAILURE = 1;

	public static void main(final String args[]) {

		/* read and manipulate args */

		if(args.length != 1) {
			System.err.printf("Wrong number of args: <xml>.\n");
			System.exit(EXIT_FAILURE);
		}

		System.err.printf("Nplus <%s>\n", args[0]);

		String xml = args[0];

		/* read xml; why doesn't it throw something?; this is so sketch . . . */
		System.err.printf("Appempting to read StateMachine from <%s>.\n", xml);
		StateMachine sm = PersistenceStateMachine.loadStateMachine(xml);
		for(Transition t : sm.getTransitions()) {
			
		}
		String targetClass = basicFilename(sm.getClassName());
		String testClass   = String.format("GeneratedTest%s", targetClass);

		/* create the header */
		System.out.printf("/** Auto-generated by Nplus. */\n\n");
		if(sm.getPackageName().length() > 0) {
			System.out.printf("package %s;\n\n", sm.getPackageName());
		}
		System.out.printf("import org.junit.Test;\n");
		System.out.printf("import org.junit.Assert;\n\n");
		System.out.printf("import java.util.function.Predicate;\n\n");
		System.out.printf("public class %s {\n\n", testClass);
		for(State s : sm.getStates()) {
			if("start".compareTo(s.getName()) == 0) continue;
			System.out.printf("\tstatic final Predicate<%s> isState%s = (m) -> m.getState() == %s.State.%s;\n", targetClass, s.getName(), targetClass, s.getName());
		}
		System.out.printf("\n");

		/* dfs */
		State nextState;
		while(sm.getStartState().isVisited() == false) {
			System.out.printf("\t@Test\n");
			System.out.printf("\tpublic void test() {\n");
			System.out.printf("\t\t%s test = new %s(/* assumes no input constructor is defined */);\n", targetClass, targetClass);
			/* this is incorrect */
			for(State state = sm.getStartState(); ; state = nextState) {
				state.setVisited();
				nextState = null;
				for(Transition t : state.getOut()) {
					System.out.printf("/*%s: %s?*/\n", state.getName(), t);
					if(!t.getTo().isFinished () && t.getTo() != state) {
						System.out.printf("/*Yes.*/\n");
						nextState = t.getTo();
						break;
					}
				}
				nextState = null;
				if(nextState == null) {
					state.setVisited();
					break;
				}
			}
			System.out.printf("\t}\n\n");
		}

		/* footer */
		System.out.printf("}\n");

	}

	/* /dir/dir/dir/foo.bar -> foo */
	private static String basicFilename(final String filename) {
		int begin = filename.indexOf(File.separatorChar) + 1;
		int end   = filename.indexOf('.', begin);
		return (end == -1) ? filename.substring(begin) : filename.substring(begin, end);
	}

	/** /dir/dir/dir/foo.bar -> dir.dir.dir
	 @fixme	This is really delicate. */
	private static String pathToPackage(final String filename) {
		int last  = filename.lastIndexOf(File.separatorChar);
		if(last == -1) return null;
		int first = filename.indexOf(File.separatorChar);
		if(first == -1 || first == last) return null;
		return filename.substring(first + 1, last).replace(File.separatorChar, '.');
	}

	/** /dir/dir/dir/foo.bar -> foo.bar
	 @fixme	This is really delicate. */
	private static String extractFilename(final String filename) {
		int last = filename.lastIndexOf(File.separatorChar) + 1;
		return filename.substring(last);
	}

	/** /dir/dir/dir/foo.bar -> foo
	 @fixme	This is really delicate. */
	private static String extractClass(final String filename) {
		String fn = extractFilename(filename);
		int last = fn.lastIndexOf('.');
		if(last == -1) return null;
		return fn.substring(0, last);
	}

	/** Constructor.
	@param ex Something. */
	public Nplus(final String xmlName, final String sourcePath) {
	}

	/** Javadocs {@link URL}.
	 <p>
	 More.
	 
	 @param p			Thing.
	 @return			Thing.
	 @throws Exception	Thing.
	 @see				package.Class#method(Type)
	 @see				#field
	 @since				1.0
	 @deprecated		Ohnoz. */

	/** @return A synecdochical {@link String}. */
	public String toString() {
		return "Hi";
	}

}
