/** Auto-generated by Nplus. */

package ca.mcgill.ecse429.conformancetest.legislation;

import org.junit.Test;
import org.junit.Assert;

public class GeneratedTestLegislation {

	@Test
	public void one() {
		Legislation test = new Legislation(/* assumes no input constructor is defined */);
	}

	/* start */
	static private void teststart() {
	}

	/* inPreparation */
	static private void testinPreparation() {
	}

	/* inHouseOfCommons */
	static private void testinHouseOfCommons() {
	}

	/* inSenate */
	static private void testinSenate() {
	}

	/* finalized */
	static private void testfinalized() {
	}

}
