/** Auto-generated by Nplus. */

package ca.mcgill.ecse429.conformancetest.ccoinbox;

import org.junit.Test;
import org.junit.Assert;

import java.util.function.Predicate;

public class GeneratedTestCCoinBox {

	static final Predicate<CCoinBox> isStateempty = (m) -> m.getState() == CCoinBox.State.empty;
	static final Predicate<CCoinBox> isStatenotAllowed = (m) -> m.getState() == CCoinBox.State.notAllowed;
	static final Predicate<CCoinBox> isStateallowed = (m) -> m.getState() == CCoinBox.State.allowed;

	static CCoinBox test;

	@Test
	void TestPath1() {
		/* make a new test class; assumes no-arg con'r is good */
		test = new CCoinBox();

		/*
		(notAllowed->allowed)
		(empty->notAllowed)
		(start->empty)
		*/
		/* start -- empty */
		/* empty -- notAllowed */
		/* notAllowed -- allowed */
	}

}
